### ISSUE TITLE
Анимация элементов и переходов

### ISSUE THREAD

**Issue by yepninja** [siyanie/siyanie-ui#15]
### Предлоадер
- [ ] загрузка сайта (добавить появление движение и исчезновение блика) #16
### Видео
- [x] наведение на видео на главной, раздвигая границ #17
- [x] кнопка Play при наведении #19
- [ ] появление и проигрывание видео после нажатия на кнопку плей #18
- [ ] обратного исчезновения видео #20
### Обратный звонок
- [ ] появление и исчезновения формы #22
- [ ] поведения самой формы #23
- [ ] наведение на номер телефона в шапке #21
### Страницы
- [ ] появление страниц (фото, шапка и подвал, контент, фраза)
- [ ] переход между страницами (появление анимация смена заставки на страницу) #26
- [ ] смена контента на страницах #27
- [ ] появление страницы Проекты
- [ ] поведения при наведении проектов на этой странице
- [ ] появление страницы проекта после нажатия на проект из прямоугольника
- [ ] появление дополненной страницы проекты, анимация скроллинга
- [ ] появление страницы проекта из квадрата
- [ ] появление контента на странице Проекта
- [ ] увеличение сертификатов #30
- [ ] контент на странице Контакты
- [ ] появление цифр в подразделе О компании - О нас на 4ом слайде #28
- [ ] появление логотипов в подразделе О компании - О нас на 5ом слайде #29
- [ ] подраздел История компании
### Меню
- [ ] появление подменю
- [ ] смены активного раздела в подменю
### Подвал
- [ ] наведение на соц сети #24
- [ ] наведение на логотип #25
- [ ] наведение на ссылки
